/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import project.*;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author w
 */
public class Option_1_Frame extends javax.swing.JFrame {

    String[] keyForWriteOut;

    /**
     * Creates new form Option_1_Frame
     */
    public Option_1_Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameInputField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id_InputField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        genButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        outTextArea = new javax.swing.JTextArea();
        lengthOption = new javax.swing.JComboBox();
        reButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        nKey = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("การสร้างรหัสจากข้อมูลนำเข้า");

        nameInputField.setText("Enter Name For Build Key");
        nameInputField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameInputFieldMouseClicked(evt);
            }
        });
        nameInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameInputFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter Name");

        jLabel2.setText("Enter ID");

        id_InputField.setText("Enter ID For Build Key");
        id_InputField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                id_InputFieldMouseClicked(evt);
            }
        });
        id_InputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_InputFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Enter Length");

        jLabel4.setText("Enter Amount Password ");

        genButton.setText("Generate");
        genButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genButtonActionPerformed(evt);
            }
        });

        outTextArea.setColumns(20);
        outTextArea.setRows(5);
        jScrollPane1.setViewportView(outTextArea);

        lengthOption.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        lengthOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lengthOptionActionPerformed(evt);
            }
        });

        reButton.setText("Reset");
        reButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save to File");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        nKey.setText("Enter Number For Output");
        nKey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nKeyMouseClicked(evt);
            }
        });
        nKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nKeyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lengthOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(nameInputField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(id_InputField)))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nKey, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(genButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(reButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saveButton)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(id_InputField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lengthOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genButton)
                    .addComponent(reButton)
                    .addComponent(saveButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameInputFieldActionPerformed

    private void lengthOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lengthOptionActionPerformed

    }//GEN-LAST:event_lengthOptionActionPerformed

    private void reButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reButtonActionPerformed
        this.outTextArea.setText(null);
    }//GEN-LAST:event_reButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String desOut, outName = "Key";

        try {

            desOut = JOptionPane.showInputDialog(this, "Save to...\nWill save as *\\Key.txt", "");

            File f = new File(desOut + "\\" + outName + ".txt");
            FileWriter out = new FileWriter(f);

            BufferedWriter bw = new BufferedWriter(out);

            for (int i = 0; i < this.keyForWriteOut.length; i++) {
                bw.write(this.keyForWriteOut[i]);
                bw.newLine();
            }

            bw.close();

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Sorry, Can't access this address");
        } finally {
            int exit = JOptionPane.showConfirmDialog(this, "Do you want to exit program? \nNo, will reset text field.");
            if (exit == 0) {
                System.exit(0);
            } else if (exit == 1) {
                this.outTextArea.setText(null);
            }
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void id_InputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_InputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_InputFieldActionPerformed

    private void nKeyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nKeyMouseClicked
        this.nKey.setText(null);
    }//GEN-LAST:event_nKeyMouseClicked

    private void nKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nKeyActionPerformed

    }//GEN-LAST:event_nKeyActionPerformed

    private void id_InputFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id_InputFieldMouseClicked
        this.id_InputField.setText(null);
    }//GEN-LAST:event_id_InputFieldMouseClicked

    private void nameInputFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameInputFieldMouseClicked
        this.nameInputField.setText(null);
    }//GEN-LAST:event_nameInputFieldMouseClicked

    private void genButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genButtonActionPerformed
        this.outTextArea.setText(null);

        int length, amount;
        String name, ID;

        length = this.lengthOption.getSelectedIndex() + 6;
        amount = Integer.parseInt(this.nKey.getText());
        name = this.nameInputField.getText();
        ID = this.id_InputField.getText();

        NameandID ni = new NameandID(length, amount, name, ID);

        String[] keyForPrintOut = new String[amount];
        keyForWriteOut = keyForPrintOut = ni.compilePassForGUI();

        int i = 0;
        while (i < keyForPrintOut.length) {
            this.outTextArea.insert(keyForPrintOut[i] + "\n", 0);
            i++;
        }
    }//GEN-LAST:event_genButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Option_1_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Option_1_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Option_1_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Option_1_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Option_1_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton genButton;
    private javax.swing.JTextField id_InputField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox lengthOption;
    private javax.swing.JTextField nKey;
    private javax.swing.JTextField nameInputField;
    private javax.swing.JTextArea outTextArea;
    private javax.swing.JButton reButton;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
